---
- hosts: switches
  vars:
    vlan_id: 998
    vlan_name: Ansible_VLAN

  tasks:
    - name: Ensure Fa2/0/5 is configured for access vlan 20
      cisco.ios.ios_l2_interface:
        name: FastEthernet2/0/5
        mode: access
        access_vlan: { { vlan_id } }
